typography_spectrum: 0.7970822763163596
content_rating:
  adult: true
color:
  brandStrength: 0.011750630801543593
  lightness: 0.07925660558976233
  saturation: 0.9555741548538208
  rhythmicContrast: 0.88410051073879
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.8722169110551476
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ddd636cc-1ba8-4bc8-970c-f817ba3d827a.png
name: Chaturbate Plus
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff854839-fc0d-42ef-a68c-35bb9a6b1d90.ico
title: AI powered Chaturbate Cam Selection and Presentation
