typography_spectrum: 0.7970822763163596
content_rating:
  adult: true
color:
  brandStrength: 0.2832884138915688
  lightness: 0.7472120469901711
  saturation: 0.23171554179862142
  rhythmicContrast: 0.8415345966350287
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.1836822333279997
author:
  name: JOKER
  email: ''
  url: 'https://chaturbate.plus'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ddd636cc-1ba8-4bc8-970c-f817ba3d827a.png
name: Chaturbate Plus
title: THE ACT OF MASTURBATING WHILE CHATTING ONLINE
