typography_spectrum: 0.21913888258859515
content_rating:
  adult: true
color:
  brandStrength: 0.7702258464414626
  lightness: 0.04628110188059509
  saturation: 0.6386368132662028
  rhythmicContrast: 0.4412912300322205
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
layout_spectrum: 0.02922703349031508
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ddd636cc-1ba8-4bc8-970c-f817ba3d827a.png
name: Chaturbate Plus
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff854839-fc0d-42ef-a68c-35bb9a6b1d90.ico
title: AI powered Chaturbate Cam Selection and Presentation
